#!/bin/bash


set -e
lasthash=`git log --decorate=full --all --pretty=format:'%h %d'  |grep 'refs/tags'|head -1|awk '{print $1}'`
lasttag=`git describe --tags $lasthash`

echo "Previous tag was $lasttag"

read -e -p "Enter ${CYAN}new tag${OFF}: " -i "$newtag" newtag

read -e -p  "Press enter to tag $newtag: "

gitbase=`git rev-parse --show-toplevel`
echo $newtag > $gitbase/VERSION
git add $gitbase/VERSION
git commit -m "Set version to $newtag"
#git push origin
git push github
git tag -a $newtag -m "Tagged version:$newtag"
git push --tags
